name: MCP Smoke

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/mcp/**'
      - '.github/workflows/mcp-smoke.yml'
  pull_request:
    paths:
      - '.github/mcp/**'
      - '.github/workflows/mcp-smoke.yml'

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install MCP requirements
        run: |
          set -e
          for req in .github/mcp/*/requirements.txt; do
            if [ -f "$req" ]; then
              echo "Installing $req"
              pip install -r "$req"
            fi
          done

      - name: Run MCP smoke tests
        run: |
          chmod +x .github/mcp/smoke-test.sh
          .github/mcp/smoke-test.sh
