/**
 * CosmosDBGenerator - Azure Cosmos DB Code Generator
 * 
 * Generates Cosmos DB containers, stored procedures, triggers,
 * user-defined functions, and index policies.
 */

const BaseGenerator = require('./BaseGenerator');

class CosmosDBGenerator extends BaseGenerator {
  constructor(options = {}) {
    super({
      name: 'CosmosDBGenerator',
      framework: 'cosmos-db',
      version: 'latest',
      language: 'javascript',
      ...options
    });
    
    this.templatePath = 'database/cosmos-db';
    this.supportedTypes = ['container', 'storedProcedure', 'trigger', 'udf', 'indexPolicy'];
  }

  /**
   * Generate a Cosmos DB container definition
   */
  async generateContainer(context) {
    const { 
      name, 
      partitionKey,
      uniqueKeys = [],
      indexingPolicy,
      defaultTtl,
      throughput
    } = context;
    
    const templateData = {
      id: name,
      partitionKey: this.buildPartitionKey(partitionKey),
      uniqueKeyPolicy: this.buildUniqueKeyPolicy(uniqueKeys),
      indexingPolicy: indexingPolicy || this.buildDefaultIndexPolicy(),
      defaultTtl,
      throughput,
      hasUniqueKeys: uniqueKeys.length > 0,
      hasDefaultTtl: defaultTtl !== undefined,
      hasThroughput: throughput !== undefined
    };
    
    return JSON.stringify(templateData, null, 2);
  }

  /**
   * Generate a Cosmos DB stored procedure
   */
  async generateStoredProcedure(context) {
    const { 
      name, 
      parameters = [],
      body,
      description
    } = context;
    
    const templateData = {
      id: name,
      parameters,
      body: body || this.getDefaultSprocBody(name),
      description
    };
    
    return this.generateStoredProcedureCode(templateData);
  }

  /**
   * Generate a Cosmos DB trigger
   */
  async generateTrigger(context) {
    const { 
      name, 
      type = 'pre',
      operation = 'all',
      body
    } = context;
    
    const templateData = {
      id: name,
      triggerType: type === 'pre' ? 'Pre' : 'Post',
      triggerOperation: this.getTriggerOperation(operation),
      body: body || this.getDefaultTriggerBody(name, type)
    };
    
    return this.generateTriggerCode(templateData);
  }

  /**
   * Generate a Cosmos DB user-defined function
   */
  async generateUdf(context) {
    const { 
      name, 
      parameters = [],
      body,
      description
    } = context;
    
    const templateData = {
      id: name,
      parameters,
      body: body || this.getDefaultUdfBody(name),
      description
    };
    
    return this.generateUdfCode(templateData);
  }

  /**
   * Generate a Cosmos DB index policy
   */
  async generateIndexPolicy(context) {
    const { 
      indexingMode = 'consistent',
      automatic = true,
      includedPaths = [],
      excludedPaths = [],
      compositeIndexes = [],
      spatialIndexes = []
    } = context;
    
    const policy = {
      indexingMode,
      automatic,
      includedPaths: this.buildIncludedPaths(includedPaths),
      excludedPaths: this.buildExcludedPaths(excludedPaths)
    };
    
    if (compositeIndexes.length > 0) {
      policy.compositeIndexes = this.buildCompositeIndexes(compositeIndexes);
    }
    
    if (spatialIndexes.length > 0) {
      policy.spatialIndexes = this.buildSpatialIndexes(spatialIndexes);
    }
    
    return JSON.stringify(policy, null, 2);
  }

  // Code generation methods
  generateStoredProcedureCode(data) {
    return `/**
 * Stored Procedure: ${data.id}
 * ${data.description || 'Generated by AgenticCoder'}
 */
function ${this.toCamelCase(data.id)}(${data.parameters.map(p => p.name).join(', ')}) {
    var context = getContext();
    var container = context.getCollection();
    var response = context.getResponse();
    
    ${data.body}
}`;
  }

  generateTriggerCode(data) {
    return `/**
 * ${data.triggerType} Trigger: ${data.id}
 * Operation: ${data.triggerOperation}
 * Generated by AgenticCoder
 */
function ${this.toCamelCase(data.id)}() {
    var context = getContext();
    var request = context.getRequest();
    var response = context.getResponse();
    
    ${data.body}
}`;
  }

  generateUdfCode(data) {
    return `/**
 * User Defined Function: ${data.id}
 * ${data.description || 'Generated by AgenticCoder'}
 */
function ${this.toCamelCase(data.id)}(${data.parameters.map(p => p.name).join(', ')}) {
    ${data.body}
}`;
  }

  // Helper methods
  buildPartitionKey(partitionKey) {
    if (!partitionKey) {
      return { paths: ['/id'], kind: 'Hash' };
    }
    
    if (typeof partitionKey === 'string') {
      return { paths: [partitionKey.startsWith('/') ? partitionKey : `/${partitionKey}`], kind: 'Hash' };
    }
    
    return {
      paths: partitionKey.paths || [partitionKey.path],
      kind: partitionKey.kind || 'Hash',
      version: partitionKey.version || 2
    };
  }

  buildUniqueKeyPolicy(uniqueKeys) {
    if (uniqueKeys.length === 0) return undefined;
    
    return {
      uniqueKeys: uniqueKeys.map(uk => ({
        paths: Array.isArray(uk) ? uk : uk.paths
      }))
    };
  }

  buildDefaultIndexPolicy() {
    return {
      indexingMode: 'consistent',
      automatic: true,
      includedPaths: [
        { path: '/*' }
      ],
      excludedPaths: [
        { path: '/"_etag"/?' }
      ]
    };
  }

  buildIncludedPaths(paths) {
    if (paths.length === 0) {
      return [{ path: '/*' }];
    }
    
    return paths.map(p => {
      if (typeof p === 'string') {
        return { path: p };
      }
      return {
        path: p.path,
        indexes: p.indexes
      };
    });
  }

  buildExcludedPaths(paths) {
    const defaultExcluded = [{ path: '/"_etag"/?' }];
    
    if (paths.length === 0) {
      return defaultExcluded;
    }
    
    return [
      ...defaultExcluded,
      ...paths.map(p => ({ path: typeof p === 'string' ? p : p.path }))
    ];
  }

  buildCompositeIndexes(indexes) {
    return indexes.map(idx => 
      idx.map(col => ({
        path: col.path || col,
        order: col.order || 'ascending'
      }))
    );
  }

  buildSpatialIndexes(indexes) {
    return indexes.map(idx => ({
      path: idx.path,
      types: idx.types || ['Point', 'Polygon', 'LineString']
    }));
  }

  getTriggerOperation(operation) {
    const ops = {
      all: 'All',
      create: 'Create',
      update: 'Update',
      delete: 'Delete',
      replace: 'Replace'
    };
    return ops[operation.toLowerCase()] || 'All';
  }

  getDefaultSprocBody(name) {
    return `// TODO: Implement stored procedure logic
    
    // Example: Query documents
    var isAccepted = container.queryDocuments(
        container.getSelfLink(),
        'SELECT * FROM c',
        function (err, documents, options) {
            if (err) throw err;
            response.setBody(documents);
        }
    );
    
    if (!isAccepted) {
        throw new Error('Query was not accepted by the server.');
    }`;
  }

  getDefaultTriggerBody(name, type) {
    if (type === 'pre') {
      return `// Pre-trigger: Modify document before operation
    var document = request.getBody();
    
    // Add timestamp
    document.modifiedAt = new Date().toISOString();
    
    // Validate document
    if (!document.id) {
        throw new Error('Document must have an id.');
    }
    
    request.setBody(document);`;
    }
    
    return `// Post-trigger: Execute after operation
    var document = response.getBody();
    
    // Log operation
    console.log('Document processed: ' + document.id);`;
  }

  getDefaultUdfBody(name) {
    return `// TODO: Implement function logic
    // Example: Format a string
    return input;`;
  }

  /**
   * Generate a TypeScript/JavaScript client helper
   */
  async generateClientHelper(context) {
    const { 
      containerName, 
      partitionKeyPath,
      operations = ['create', 'read', 'update', 'delete', 'query']
    } = context;
    
    const className = this.toPascalCase(containerName) + 'Repository';
    
    const lines = [];
    lines.push(`import { Container, CosmosClient, Database } from '@azure/cosmos';`);
    lines.push('');
    lines.push(`export class ${className}<T extends { id: string }> {`);
    lines.push('  private container: Container;');
    lines.push('');
    lines.push('  constructor(client: CosmosClient, databaseId: string) {');
    lines.push(`    this.container = client.database(databaseId).container('${containerName}');`);
    lines.push('  }');
    lines.push('');
    
    if (operations.includes('create')) {
      lines.push('  async create(item: T): Promise<T> {');
      lines.push('    const { resource } = await this.container.items.create(item);');
      lines.push('    return resource as T;');
      lines.push('  }');
      lines.push('');
    }
    
    if (operations.includes('read')) {
      lines.push(`  async read(id: string, partitionKey: string): Promise<T | undefined> {`);
      lines.push('    try {');
      lines.push('      const { resource } = await this.container.item(id, partitionKey).read<T>();');
      lines.push('      return resource;');
      lines.push('    } catch (error: any) {');
      lines.push('      if (error.code === 404) return undefined;');
      lines.push('      throw error;');
      lines.push('    }');
      lines.push('  }');
      lines.push('');
    }
    
    if (operations.includes('update')) {
      lines.push('  async update(id: string, partitionKey: string, item: Partial<T>): Promise<T> {');
      lines.push('    const { resource } = await this.container.item(id, partitionKey).replace({ ...item, id });');
      lines.push('    return resource as T;');
      lines.push('  }');
      lines.push('');
    }
    
    if (operations.includes('delete')) {
      lines.push('  async delete(id: string, partitionKey: string): Promise<void> {');
      lines.push('    await this.container.item(id, partitionKey).delete();');
      lines.push('  }');
      lines.push('');
    }
    
    if (operations.includes('query')) {
      lines.push('  async query(query: string, parameters?: { name: string; value: any }[]): Promise<T[]> {');
      lines.push('    const { resources } = await this.container.items');
      lines.push('      .query<T>({ query, parameters })');
      lines.push('      .fetchAll();');
      lines.push('    return resources;');
      lines.push('  }');
      lines.push('');
    }
    
    lines.push('}');
    
    return lines.join('\n');
  }
}

module.exports = CosmosDBGenerator;
