/**
 * Bicep Application Insights Template
 * 
 * Azure Application Insights deployment template
 */

const template = `// Azure Application Insights
// Generated by AgenticCoder

targetScope = 'resourceGroup'

// ============================================================================
// Parameters
// ============================================================================

@description('The name of Application Insights')
param appInsightsName string

@description('Location for all resources')
param location string = resourceGroup().location

@description('The type of application')
@allowed([
  'web'
  'other'
  'java'
  'phone'
])
param applicationType string = 'web'

@description('Retention in days')
@minValue(30)
@maxValue(730)
param retentionInDays int = 90

@description('Daily data cap in GB')
param dailyQuotaGb int = -1

@description('Enable sampling')
param samplingPercentage int = 100

@description('Disable IP masking')
param disableIpMasking bool = false

@description('Log Analytics Workspace ID')
param logAnalyticsWorkspaceId string = ''

@description('Tags for all resources')
param tags object = {}

// ============================================================================
// Variables
// ============================================================================

var appInsightsNameFormatted = 'appi-\${appInsightsName}'
var workspaceNameFormatted = 'log-\${appInsightsName}'
var commonTags = union(tags, {
  'managed-by': 'bicep'
})

// ============================================================================
// Resources
// ============================================================================

// Log Analytics Workspace (if not provided)
resource logAnalyticsWorkspace 'Microsoft.OperationalInsights/workspaces@2022-10-01' = if (empty(logAnalyticsWorkspaceId)) {
  name: workspaceNameFormatted
  location: location
  tags: commonTags
  properties: {
    sku: {
      name: 'PerGB2018'
    }
    retentionInDays: retentionInDays
    features: {
      enableLogAccessUsingOnlyResourcePermissions: true
    }
    publicNetworkAccessForIngestion: 'Enabled'
    publicNetworkAccessForQuery: 'Enabled'
  }
}

// Application Insights
resource appInsights 'Microsoft.Insights/components@2020-02-02' = {
  name: appInsightsNameFormatted
  location: location
  tags: commonTags
  kind: applicationType
  properties: {
    Application_Type: applicationType
    WorkspaceResourceId: empty(logAnalyticsWorkspaceId) ? logAnalyticsWorkspace.id : logAnalyticsWorkspaceId
    RetentionInDays: retentionInDays
    IngestionMode: 'LogAnalytics'
    publicNetworkAccessForIngestion: 'Enabled'
    publicNetworkAccessForQuery: 'Enabled'
    DisableIpMasking: disableIpMasking
    SamplingPercentage: samplingPercentage
  }
}

// Smart Detection Rules
{{#if enableSmartDetection}}
resource failureAnomaliesDetector 'Microsoft.AlertsManagement/smartDetectorAlertRules@2021-04-01' = {
  name: 'Failure Anomalies - \${appInsights.name}'
  location: 'global'
  tags: commonTags
  properties: {
    description: 'Failure Anomalies notifies you of an unusual rise in the rate of failed HTTP requests or dependency calls.'
    state: 'Enabled'
    severity: 'Sev3'
    frequency: 'PT1M'
    detector: {
      id: 'FailureAnomaliesDetector'
    }
    scope: [
      appInsights.id
    ]
    actionGroups: {
      groupIds: []
    }
  }
}
{{/if}}

// ============================================================================
// Outputs
// ============================================================================

@description('The name of Application Insights')
output appInsightsName string = appInsights.name

@description('The resource ID of Application Insights')
output appInsightsId string = appInsights.id

@description('The instrumentation key')
output instrumentationKey string = appInsights.properties.InstrumentationKey

@description('The connection string')
output connectionString string = appInsights.properties.ConnectionString

@description('Log Analytics Workspace ID')
output logAnalyticsWorkspaceId string = empty(logAnalyticsWorkspaceId) ? logAnalyticsWorkspace.id : logAnalyticsWorkspaceId
`;

/**
 * Prepare variables for Application Insights template
 */
function prepareVariables(config) {
  return {
    enableSmartDetection: config.enableSmartDetection || false
  };
}

module.exports = {
  template,
  prepareVariables
};
