/**
 * Init Command
 * 
 * Initializes a new AgenticCoder project with the required structure.
 */

import { Command } from 'commander';
import chalk from 'chalk';
import * as fs from 'fs';
import * as path from 'path';

export const initCommand = new Command('init')
  .description('Initialize a new AgenticCoder project')
  .option('-n, --name <name>', 'Project name', 'my-agentic-project')
  .option('-t, --template <template>', 'Project template (basic, fullstack, api)', 'basic')
  .option('-d, --directory <dir>', 'Target directory', '.')
  .option('--force', 'Overwrite existing files')
  .action(async (options) => {
    console.log(chalk.bold('\n🚀 Initializing AgenticCoder Project\n'));
    
    const targetDir = path.resolve(options.directory);
    const projectName = options.name;
    
    console.log(chalk.gray(`  Project: ${projectName}`));
    console.log(chalk.gray(`  Template: ${options.template}`));
    console.log(chalk.gray(`  Directory: ${targetDir}\n`));
    
    try {
      // Create project structure
      const directories = [
        '',
        'src',
        'src/agents',
        'src/config',
        'src/generated',
        'tests',
        '.agentic'
      ];
      
      for (const dir of directories) {
        const fullPath = path.join(targetDir, dir);
        if (!fs.existsSync(fullPath)) {
          fs.mkdirSync(fullPath, { recursive: true });
          console.log(chalk.green(`  ✓ Created ${dir || '.'}`));
        }
      }
      
      // Create config file
      const configPath = path.join(targetDir, '.agentic', 'config.json');
      if (!fs.existsSync(configPath) || options.force) {
        const config = {
          projectName,
          version: '1.0.0',
          template: options.template,
          created: new Date().toISOString(),
          settings: {
            outputDir: './src/generated',
            securityEnabled: true,
            mcpEnabled: true
          },
          agents: {
            codeAgent: { enabled: true },
            securityAgent: { enabled: true },
            orchestrator: { enabled: true }
          }
        };
        fs.writeFileSync(configPath, JSON.stringify(config, null, 2));
        console.log(chalk.green('  ✓ Created .agentic/config.json'));
      }
      
      // Create package.json if it doesn't exist
      const packagePath = path.join(targetDir, 'package.json');
      if (!fs.existsSync(packagePath)) {
        const packageJson = {
          name: projectName,
          version: '1.0.0',
          description: `${projectName} - Generated by AgenticCoder`,
          type: 'module',
          scripts: {
            generate: 'agentic generate',
            scan: 'agentic scan ./src',
            status: 'agentic status'
          },
          dependencies: {},
          devDependencies: {}
        };
        fs.writeFileSync(packagePath, JSON.stringify(packageJson, null, 2));
        console.log(chalk.green('  ✓ Created package.json'));
      }
      
      // Create README.md
      const readmePath = path.join(targetDir, 'README.md');
      if (!fs.existsSync(readmePath) || options.force) {
        const readme = `# ${projectName}

Generated by [AgenticCoder](https://github.com/AgenticCoder).

## Getting Started

\`\`\`bash
# Check project status
agentic status

# Generate code
agentic generate --scenario S01

# Run security scan
agentic scan ./src
\`\`\`

## Project Structure

\`\`\`
${projectName}/
├── .agentic/           # AgenticCoder configuration
│   └── config.json     # Project settings
├── src/
│   ├── agents/         # Custom agents
│   ├── config/         # Configuration files
│   └── generated/      # Generated code output
└── tests/              # Test files
\`\`\`
`;
        fs.writeFileSync(readmePath, readme);
        console.log(chalk.green('  ✓ Created README.md'));
      }
      
      console.log(chalk.bold.green('\n✅ Project initialized successfully!\n'));
      console.log(chalk.gray('Next steps:'));
      console.log(chalk.cyan('  1. cd ' + (options.directory === '.' ? projectName : options.directory)));
      console.log(chalk.cyan('  2. agentic status'));
      console.log(chalk.cyan('  3. agentic generate --scenario S01\n'));
      
    } catch (error) {
      console.error(chalk.red('\n❌ Initialization failed:'), (error as Error).message);
      process.exit(1);
    }
  });
