/**
 * Bicep SQL Database Template
 * 
 * Azure SQL Database deployment template
 */

const template = `// Azure SQL Database
// Generated by AgenticCoder

targetScope = 'resourceGroup'

// ============================================================================
// Parameters
// ============================================================================

@description('The name of the SQL Server')
@minLength(1)
@maxLength(63)
param serverName string

@description('The name of the SQL Database')
@minLength(1)
@maxLength(128)
param databaseName string

@description('Location for all resources')
param location string = resourceGroup().location

@description('The administrator login for the SQL Server')
@secure()
param adminLogin string

@description('The administrator password for the SQL Server')
@secure()
param adminPassword string

@description('The tier of the SQL Database')
@allowed([
  'Basic'
  'Standard'
  'Premium'
  'GeneralPurpose'
  'BusinessCritical'
  'Hyperscale'
])
param tier string = '{{defaultTier}}'

@description('The SKU name')
param skuName string = '{{defaultSku}}'

@description('The maximum size of the database in bytes')
param maxSizeBytes int = {{defaultMaxSize}}

@description('Enable Azure AD authentication only')
param enableAzureADOnlyAuth bool = false

@description('Azure AD admin object ID')
param azureADAdminObjectId string = ''

@description('Azure AD admin login name')
param azureADAdminLogin string = ''

@description('Enable public network access')
param publicNetworkAccess string = 'Enabled'

@description('Tags for all resources')
param tags object = {}

// ============================================================================
// Variables
// ============================================================================

var sqlServerName = 'sql-\${serverName}'
var sqlDatabaseName = 'sqldb-\${databaseName}'
var commonTags = union(tags, {
  'managed-by': 'bicep'
})

// ============================================================================
// Resources
// ============================================================================

// SQL Server
resource sqlServer 'Microsoft.Sql/servers@2023-05-01-preview' = {
  name: sqlServerName
  location: location
  tags: commonTags
  properties: {
    administratorLogin: enableAzureADOnlyAuth ? null : adminLogin
    administratorLoginPassword: enableAzureADOnlyAuth ? null : adminPassword
    version: '12.0'
    minimalTlsVersion: '1.2'
    publicNetworkAccess: publicNetworkAccess
  }
}

// Azure AD Administrator
resource azureADAdmin 'Microsoft.Sql/servers/administrators@2023-05-01-preview' = if (!empty(azureADAdminObjectId)) {
  parent: sqlServer
  name: 'ActiveDirectory'
  properties: {
    administratorType: 'ActiveDirectory'
    login: azureADAdminLogin
    sid: azureADAdminObjectId
    tenantId: subscription().tenantId
  }
}

// SQL Database
resource sqlDatabase 'Microsoft.Sql/servers/databases@2023-05-01-preview' = {
  parent: sqlServer
  name: sqlDatabaseName
  location: location
  tags: commonTags
  sku: {
    name: skuName
    tier: tier
  }
  properties: {
    collation: 'SQL_Latin1_General_CP1_CI_AS'
    maxSizeBytes: maxSizeBytes
    zoneRedundant: tier == 'Premium' || tier == 'BusinessCritical'
    readScale: tier == 'Premium' || tier == 'BusinessCritical' ? 'Enabled' : 'Disabled'
    requestedBackupStorageRedundancy: 'Geo'
  }
}

// Firewall rule - Allow Azure Services
resource allowAzureServices 'Microsoft.Sql/servers/firewallRules@2023-05-01-preview' = {
  parent: sqlServer
  name: 'AllowAllWindowsAzureIps'
  properties: {
    startIpAddress: '0.0.0.0'
    endIpAddress: '0.0.0.0'
  }
}

// Auditing (optional)
{{#if enableAuditing}}
resource sqlAuditing 'Microsoft.Sql/servers/auditingSettings@2023-05-01-preview' = {
  parent: sqlServer
  name: 'default'
  properties: {
    state: 'Enabled'
    isAzureMonitorTargetEnabled: true
    retentionDays: 90
  }
}
{{/if}}

// ============================================================================
// Outputs
// ============================================================================

@description('The name of the SQL Server')
output serverName string = sqlServer.name

@description('The fully qualified domain name of the SQL Server')
output fullyQualifiedDomainName string = sqlServer.properties.fullyQualifiedDomainName

@description('The name of the SQL Database')
output databaseName string = sqlDatabase.name

@description('The resource ID of the SQL Server')
output serverResourceId string = sqlServer.id

@description('The resource ID of the SQL Database')
output databaseResourceId string = sqlDatabase.id

@description('Connection string (without credentials)')
output connectionString string = 'Server=tcp:\${sqlServer.properties.fullyQualifiedDomainName},1433;Initial Catalog=\${sqlDatabase.name};Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'
`;

/**
 * Prepare variables for SQL Database template
 */
function prepareVariables(config) {
  return {
    defaultTier: config.tier || 'Standard',
    defaultSku: config.sku || 'S0',
    defaultMaxSize: config.maxSizeBytes || 2147483648, // 2GB
    enableAuditing: config.enableAuditing || false
  };
}

module.exports = {
  template,
  prepareVariables
};
